### PR TITLE
Added logo component and make logo spain

### PR DESCRIPTION
**Pull request by Ezekiel8807**
# Fixes Issue
PR to fix issue #84

## Changes proposed
added a logo component in the component directory and make logo spin

**Requirements**
Create a component named Logo in the components folder that implements the screenshots below.
It should accept a size as prop for the different sizes on the header and footer.
The logo should rotate similar to how it does in a fresh create react app installation [as shown on this GIF](https://opensource.com/sites/default/files/uploads/react.gif).
Obtain the logo from the Figma design. Use [THIS VIDEO](https://www.youtube.com/watch?v=T3rUlKf40M0) as a guide

Acceptance Criteria
- [x] The implementation should match the design.

Screenshots
shoot1

## Note to reviewers
The Logo spin animation was performed using the tailwind css animation class.

### CODE REVIEW

**Comment by Ezekiel8807** [comment]
Can you please give me write access, so I can resolve the conflict

**Comment by antosan** [comment]
> Can you please give me write access, so I can resolve the conflict

@Ezekiel8807 You need to check out the `develop` branch on your fork and make the changes there. You are currently working on the `main` branch and that is why you have conflicts.

image

**Comment by Ezekiel8807** [comment]
which one is your main respository? main or develop

**Comment by antosan** [comment]
> which one is your main respository? main or develop

The default branch is `develop`. I just made this switch in the repo as well to avoid future confusion.

**Pull request closed without merging**
