### PR TITLE
Updated Under Construction banner [ Fixes #51 ]

### LINKED ISSUE #51: Create an "🚧Under Construction🚧" Banner at the Top of the page
### What feature are you adding?

Adding an Under Construction Banner at the top of the page

### Describe your issue

When coming to the page for the first time in its current form, you will be met by a super basic page. Wanted a way to show new visitors that the page is currently under construction with a construction banner component at the top of the page.

##### example image

under-construction-banner

Here is also a nice article from css-tricks incase you want to take up the issue
[CSS-TRICKS ARTICLE](https://css-tricks.com/stripes-css/) on the diagonal colored stripes category.

### PR DESCRIPTION
**Pull request by king-kanda**
## Fixes Issue #51 
 
- Adding an under-construction banner 

## Changes proposed

1. Maintaining the style guide for coherence within the website.
2. Making it simple and comprehensive
3. A CTA for those who wish to join the community.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot from 2022-06-17 11-30-19

## Note to reviewers

corrections has been made to the code

### CODE REVIEW

**Comment by Lekipising** [comment]
This PR does not follow the specified project contribution guidelines. Please check [HERE](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and update the PR.

**Comment by king-kanda** [comment]
> This PR does not follow the specified project contribution guidelines. Please check [HERE](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and update the PR.

Is the update all good?

**Comment by Lekipising** [comment]
> > This PR does not follow the specified project contribution guidelines. Please check [HERE](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and update the PR.
> 
> Is the update all good?

Looks good to me. However you will need to space and format this place `cooking ,we'll` to `cooking, we'll`. 

While creating the PR, you should have been provided with this [template](https://github.com/reactdeveloperske/reactdevske-website/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) for description area. It appears you might have deleted it and wrote the description. Check it out.

**Comment by king-kanda** [comment]
Alright 👍

**Comment by orama254** [comment]
Hello @king-kanda,

thanks for making this pull request.

Unfortunately I'll have to close this pull request as it did not follow our [community guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) on claiming and working on an issue.

Feel free to checkout other issues on the issues tab, claim an issue first then make a pull request in accordance to our contribution guidelines.

**Pull request closed without merging**
