### PR TITLE
House keeping (05-04-2023)

### PR DESCRIPTION
**Pull request by orama254**
## Changes proposed
Fixes the remaining parts of #118 plus also adds additional information to the contribution guidelines.
Also added some updated workflow for end to end playwright tests

### CODE REVIEW

**Review by antosan — CHANGES_REQUESTED** [review]
@orama254 The tests seem to be failing because they do not have access to the environment variables. I usually prefer creating a `.env` file in CI similar to how we have it locally. Here is how I would suggest the `e2e.yml` workflow to be written instead to include the additional step to `Prepare .env file` (the top-level `env:` key-value pair can be removed):

```yml
name: End-to-end Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare .env file
        run: |
          rm -f .env && touch .env
          echo "NEXT_PUBLIC_FORMSPREE_ID=${{ secrets.NEXT_PUBLIC_FORMSPREE_ID }}" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" >> .env
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
```

Another thing I have noticed is that we have the word "Events" appearing severally on the page and this will cause one of the tests to be ambiguous and fail. This test in `home.spec.ts` should be adjusted to be an exact match by adding `exact: true`:

```ts
test('should show Events section', async ({ page }) => {
  await expect(
    page.getByRole('heading', { name: 'Events', exact: true })
  ).toBeVisible();
});
```

**Review by antosan — CHANGES_REQUESTED** [review]
@orama254 The trace file still shows this error `You must provide a form key or hashid (e.g. useForm("myForm") or useForm("123xyz")` which means that the value of `secrets.NEXT_PUBLIC_FORMSPREE_ID` and `secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY` are undefined. Since the values do not necessarily need to be the exact keys, can you try using fake values hardcoded in the workflow file instead, like this:

```yml
      - name: Prepare .env file
        run: |
          rm -f .env && touch .env
          echo "NEXT_PUBLIC_FORMSPREE_ID=fake" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=fake" >> .env
```

**Comment by orama254** [comment]
> 
> Another thing I have noticed is that we have the word "Events" appearing severally on the page and this will cause one of the tests to be ambiguous and fail. This test in `home.spec.ts` should be adjusted to be an exact match by adding `exact: true`:
> 
> ```ts
> test('should show Events section', async ({ page }) => {
>   await expect(
>     page.getByRole('heading', { name: 'Events', exact: true })
>   ).toBeVisible();
> });
> ```
@antosan Very nice, the tests are passing.

on the requested changes above, I'm getting an error with typescript that these are the expected parameters for that:

`{ checked?: boolean | undefined; disabled?: boolean | undefined; expanded?: boolean | undefined; includeHidden?: boolean | undefined; level?: number | undefined; name?: string | RegExp | undefined; pressed?: boolean | undefined; selected?: boolean | undefined; }`

`exact: boolean` seems to be missing

**Review by kharioki — APPROVED** [review]
All tests are running and passing

**Review by antosan — APPROVED** [review]

**Pull request merged**
