### PR TITLE
Makes navbar sticky

### LINKED ISSUE #137: Make NavBar sticky
### What feature are you adding?

making the navbar component sticky

### Describe your issue

Description
I experienced an issue where upon trying to scroll down I was unable to access the navbar.
Having it reachable when scrolling would enable ease in navigating, especially if we plan to add more pages in future.

https://github.com/reactdeveloperske/reactdevske-website/assets/48207524/8318e48e-831f-4df2-a8b1-84e5bcb9279a

Solution description
Make the navbar stick to the top when scrolling.

Additional information
Here is a short demo of what it would look like. Not the final thing however, only for demo purposes.
Among the changes I would suggest is:
- Retaining the initial clear background
- Fading into a white background and black coloured text when the user starts scrolling
- Transition back into the clear background once the user scrolls back to the the top

You can add any more recommendations you see fit.

https://github.com/reactdeveloperske/reactdevske-website/assets/48207524/f078b25c-be17-4908-b3e1-c7750362708d

### PR DESCRIPTION
**Pull request by octaviookumu**
## Fixes Issue

Closes #137

## Changes proposed
- Make Navbar accessible when scrolling (Desktop and Mobile)
- When scrolling, background colour is set to white
- When having scrolled to top, background colour is reset to transparent
- Navbar component now contains code for both desktop and mobile navbars

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

- Scrolling (Desktop)
Screenshot 2023-08-22 at 22 03 35

- Scrolled to top (Desktop)
Screenshot 2023-08-22 at 22 03 27

- Scrolling (Mobile)
Screenshot 2023-08-22 at 22 03 15

- Scrolled to top (Mobile)
Screenshot 2023-08-22 at 22 02 09

### CODE REVIEW

**Comment by octaviookumu** [comment]
Hi @reactdeveloperske. Is there any further action needed on this?

**Comment by orama254** [comment]
hey @octaviookumu could you run the following commands locally, related to the failing action, on your environment then push it in a new commit?
run-commands-locally

**Comment by octaviookumu** [comment]
> hey @octaviookumu could you run the following commands locally, related to the failing action, on your environment then push it in a new commit? run-commands-locally

Okay. Let me do that. Thanks.

**Comment by octaviookumu** [comment]
Btw I noticed some existing tests are failing. Also happening on develop branch.

Screenshot 2023-10-17 at 12 12 01

**Comment by orama254** [comment]
> Btw I noticed some existing tests are failing. Also happening on develop branch.
> 
> Screenshot 2023-10-17 at 12 12 01

There seems to be an issue with webkit, thats why it's failing. Actively looking into it.

**Comment by orama254** [comment]
LGTM ✅

**Pull request merged**
